### ISSUE TITLE
Particle Update Function

### ISSUE THREAD

**Issue by AhmedHani** [TarekVito/ParticleSwarmOpt#1]
```
velocity[i] += c1 *  (rand() / (float)RAND_MAX)* (gBest[i] - features[i])
            + c2 *  (rand() / (float)RAND_MAX)*(pBestF[i] - features[i])
            +(lBest.size() ? (c2 *  (rand() / (float)RAND_MAX)*(lBest[i] - features[i])) : 0);
```

I think this isn't original formula of the update function of the particle. You have parameters 3 parameters to update the velocity, the inertial weight (w) and 2 acceleration factors (c1 and c2). So the update function would be like that.

```
velocity[i] += w *  (rand() / (float)RAND_MAX)* (gBest[i] - features[i])
            + c1 *  (rand() / (float)RAND_MAX)*(pBestF[i] - features[i])
            +(lBest.size() ? (c2 *  (rand() / (float)RAND_MAX)*(lBest[i] - features[i])) : 0);
```

And the experiments showed that the best value of w is between 0.4 to 0.9 and the acceleration factors are between 2 to 2.05. And instead of using constant c1 and c2, we can make them dynamic which we reduce there values in each iteration to slow down the particle to not make them miss the global minima of the function.

Resource: https://www.researchgate.net/publication/297245624_Particle_Swarm_Optimization_Algorithm_and_its_Codes_in_MATLAB

**Comment by TarekVito** [comment]
Yes Ahmed you're right. BTW I followed this [article](http://www.swarmintelligence.org/tutorials.php). There are still some other bugs living in it :D (That's why I'm writing under development in README file)

But surely this one will be the first to solve as soon as I replace my broken laptop's screen. (After Eid ;) )

Many thank for your comment. Appreciated.

**Comment by TarekVito** [comment]
I think you mean c1 for gBest, c2 for pBest and w for previous velocity
